import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { ProjectContext } from "../context/types.js";
import { runSafe } from "../util/exec.js";
import { log } from "../util/logger.js";

/**
 * Repo-side control plane (`ralph init --governance`).
 *
 * Ralph-side gates control what Ralph PROPOSES; these files control what
 * the repo ACCEPTS: a PR template matching Ralph's evidence sections, a
 * CI workflow running the same checks Ralph verifies, and a CODEOWNERS
 * routing high-risk paths to humans. Branch protection itself is an admin
 * action Ralph never performs — the checklist printed at the end is the
 * manual half of the setup.
 */

export interface GovernanceResult {
  created: string[];
  skipped: string[];
}

export function scaffoldGovernance(
  ctx: ProjectContext,
  root: string,
): GovernanceResult {
  const result: GovernanceResult = { created: [], skipped: [] };
  const owner = detectOwner(root);

  write(root, result, ".github/pull_request_template.md", prTemplate());
  write(root, result, ".github/CODEOWNERS", codeowners(owner));

  const checks = ctx.workspaces.flatMap((w) => w.checks);
  if (checks.length > 0) {
    write(
      root,
      result,
      ".github/workflows/ralph-checks.yml",
      checksWorkflow(ctx),
    );
  } else {
    log("  No verification checks detected — skipping ralph-checks.yml (add test/build scripts first).");
  }

  return result;
}

function write(
  root: string,
  result: GovernanceResult,
  relPath: string,
  content: string,
): void {
  const path = join(root, relPath);
  if (existsSync(path)) {
    result.skipped.push(relPath);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  result.created.push(relPath);
}

/** GitHub/Gitea repo owner from the origin remote, for CODEOWNERS routing. */
export function detectOwner(root: string): string {
  const { ok, output } = runSafe("git remote get-url origin", root);
  if (ok) {
    const match = output.match(/[/:]([^/:]+)\/[^/]+?(\.git)?\s*$/);
    if (match) return `@${match[1]}`;
  }
  return "@your-github-username";
}

function prTemplate(): string {
  return `<!-- Every PR — human or agent — is judged on the same dimensions. -->

## Goal
<!-- What was this change asked to achieve? Link the issue, sprint spec, or task. -->

## Plan
<!-- Link the plan artifact (sprint spec). What scope was declared? -->

## Evidence
<!-- What proves it works: check results, commands run, commit SHAs.
     Ralph PRs carry their evidence ledger here automatically. -->

## Risks & Rollback
<!-- Risk level, affected areas, and how to undo this change. -->

## Review checklist
- [ ] Intent matches the declared goal
- [ ] Changeset stays within the declared scope
- [ ] Evidence covers the acceptance criteria
- [ ] CI checks are green (or failures are explained above)
- [ ] No workflow, infra, or secret changes outside CODEOWNERS approval
`;
}

function codeowners(owner: string): string {
  return `# High-risk paths route to human owners — agents must never
# self-approve changes here. Generated by \`ralph init --governance\`.

# CI/CD and repository automation
/.github/ ${owner}

# Infrastructure and deployment
/infra/ ${owner}
Dockerfile ${owner}
docker-compose*.yml ${owner}
*.tf ${owner}

# Dependency and security posture
package.json ${owner}
/.env.example ${owner}
`;
}

function checksWorkflow(ctx: ProjectContext): string {
  const installCmds: Record<string, string> = {
    npm: "npm ci",
    pnpm: "corepack enable && pnpm install --frozen-lockfile",
    yarn: "corepack enable && yarn install --frozen-lockfile",
    bun: "npm install -g bun && bun install",
  };
  const installCmd = installCmds[ctx.packageManager] || "npm ci";

  const steps = ctx.workspaces
    .flatMap((w) => w.checks)
    .map((c) =>
      [
        `      - name: ${c.name}`,
        `        run: ${c.cmd}`,
        ...(c.cwd && c.cwd !== "." ? [`        working-directory: ${c.cwd}`] : []),
      ].join("\n"),
    )
    .join("\n");

  return `# Generated by \`ralph init --governance\`.
#
# Runs the same checks Ralph verifies locally, so "required status checks"
# branch protection can enforce them on every PR — including Ralph's own.
name: ralph-checks

on:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: ${installCmd}
${steps}
`;
}

/**
 * The manual half of governance: admin actions Ralph cannot (and must
 * not) perform. Printed after scaffolding so activating the control
 * plane is a checklist, not a research project.
 */
export function printGovernanceChecklist(ctx: ProjectContext): void {
  log("");
  log("Manual setup — repo admin actions Ralph never performs:");
  log("");
  log(`  1. Push the scaffolded files and merge them into ${ctx.git.baseBranch}.`);
  log(`  2. GitHub → Settings → Branches → Add branch ruleset for ${ctx.git.baseBranch}:`);
  log("       - Require a pull request before merging");
  log("       - Require review from Code Owners");
  log("       - Require status checks to pass: ralph-checks / verify");
  log("       - Block force pushes");
  log("  3. Edit .github/CODEOWNERS if the detected owner is wrong, and add");
  log("     any infra/security paths specific to this repo.");
  log("  4. (Optional) Settings → General → enable \"Automatically delete head branches\"");
  log("     to keep Ralph's merged sprint branches tidy.");
  log("");
  log("With these in place, Ralph can only propose: nothing reaches");
  log(`${ctx.git.baseBranch} without green checks and a human code-owner review.`);
}
