import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { ProjectContext } from "../context/types.js";
import { runSafe } from "../util/exec.js";
import { log } from "../util/logger.js";

/**
 * Repo-side control plane (`ralph init --governance`).
 *
 * Ralph-side gates control what Ralph PROPOSES; these files control what
 * the repo ACCEPTS: a PR template matching Ralph's evidence sections, a
 * CI workflow running the same checks Ralph verifies, and a CODEOWNERS
 * routing high-risk paths to humans. Branch protection itself is an admin
 * action Ralph never performs — the checklist printed at the end is the
 * manual half of the setup.
 */

export interface GovernanceResult {
  created: string[];
  skipped: string[];
}

export function scaffoldGovernance(
  ctx: ProjectContext,
  root: string,
): GovernanceResult {
  const result: GovernanceResult = { created: [], skipped: [] };
  const owner = detectOwner(root);

  write(root, result, ".github/pull_request_template.md", prTemplate());
  write(root, result, ".github/CODEOWNERS", codeowners(owner));

  const checks = ctx.workspaces.flatMap((w) => w.checks);
  if (checks.length > 0) {
    write(
      root,
      result,
      ".github/workflows/ralph-checks.yml",
      checksWorkflow(ctx),
    );
  } else {
    log("  No verification checks detected — skipping ralph-checks.yml (add test/build scripts first).");
  }

  write(root, result, ".github/workflows/ralph-governance-judge.yml", judgeWorkflow());
  write(root, result, ".github/scripts/ralph-judge.mjs", judgeScript());

  return result;
}

function write(
  root: string,
  result: GovernanceResult,
  relPath: string,
  content: string,
): void {
  const path = join(root, relPath);
  if (existsSync(path)) {
    result.skipped.push(relPath);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  result.created.push(relPath);
}

/** GitHub/Gitea repo owner from the origin remote, for CODEOWNERS routing. */
export function detectOwner(root: string): string {
  const { ok, output } = runSafe("git remote get-url origin", root);
  if (ok) {
    const match = output.match(/[/:]([^/:]+)\/[^/]+?(\.git)?\s*$/);
    if (match) return `@${match[1]}`;
  }
  return "@your-github-username";
}

function prTemplate(): string {
  return `<!-- Every PR — human or agent — is judged on the same dimensions. -->

## Goal
<!-- What was this change asked to achieve? Link the issue, sprint spec, or task. -->

## Plan
<!-- Link the plan artifact (sprint spec). What scope was declared? -->

## Evidence
<!-- What proves it works: check results, commands run, commit SHAs.
     Ralph PRs carry their evidence ledger here automatically. -->

## Risks & Rollback
<!-- Risk level, affected areas, and how to undo this change. -->

## Review checklist
- [ ] Intent matches the declared goal
- [ ] Changeset stays within the declared scope
- [ ] Evidence covers the acceptance criteria
- [ ] CI checks are green (or failures are explained above)
- [ ] No workflow, infra, or secret changes outside CODEOWNERS approval
`;
}

function codeowners(owner: string): string {
  return `# High-risk paths route to human owners — agents must never
# self-approve changes here. Generated by \`ralph init --governance\`.

# CI/CD and repository automation
/.github/ ${owner}

# Infrastructure and deployment
/infra/ ${owner}
Dockerfile ${owner}
docker-compose*.yml ${owner}
*.tf ${owner}

# Dependency and security posture
package.json ${owner}
/.env.example ${owner}
`;
}

function checksWorkflow(ctx: ProjectContext): string {
  const installCmds: Record<string, string> = {
    npm: "npm ci",
    pnpm: "corepack enable && pnpm install --frozen-lockfile",
    yarn: "corepack enable && yarn install --frozen-lockfile",
    bun: "npm install -g bun && bun install",
  };
  const installCmd = installCmds[ctx.packageManager] || "npm ci";

  const steps = ctx.workspaces
    .flatMap((w) => w.checks)
    .map((c) =>
      [
        `      - name: ${c.name}`,
        `        run: ${c.cmd}`,
        ...(c.cwd && c.cwd !== "." ? [`        working-directory: ${c.cwd}`] : []),
      ].join("\n"),
    )
    .join("\n");

  return `# Generated by \`ralph init --governance\`.
#
# Runs the same checks Ralph verifies locally, so "required status checks"
# branch protection can enforce them on every PR — including Ralph's own.
name: ralph-checks

on:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: ${installCmd}
${steps}
`;
}

/**
 * The manual half of governance: admin actions Ralph cannot (and must
 * not) perform. Printed after scaffolding so activating the control
 * plane is a checklist, not a research project.
 */
export function printGovernanceChecklist(ctx: ProjectContext): void {
  log("");
  log("Manual setup — repo admin actions Ralph never performs:");
  log("");
  log(`  1. Push the scaffolded files and merge them into ${ctx.git.baseBranch}.`);
  log(`  2. GitHub → Settings → Branches → Add branch ruleset for ${ctx.git.baseBranch}:`);
  log("       - Require a pull request before merging");
  log("       - Require review from Code Owners");
  log("       - Require status checks to pass: ralph-checks / verify");
  log("       - Block force pushes");
  log("  3. Edit .github/CODEOWNERS if the detected owner is wrong, and add");
  log("     any infra/security paths specific to this repo.");
  log("  4. (Optional) Settings → General → enable \"Automatically delete head branches\"");
  log("     to keep Ralph's merged sprint branches tidy.");
  log("");
  log("With these in place, Ralph can only propose: nothing reaches");
  log(`${ctx.git.baseBranch} without green checks and a human code-owner review.`);
  log("The governance judge scores every sprint/* PR automatically from GitHub API state,");
  log("independent of Ralph's own process — no API keys required.");
}

function judgeWorkflow(): string {
  return `# Generated by \`ralph init --governance\`.
# Scores every sprint/* PR for governance compliance from outside Ralph's
# own process — queries real GitHub API state and evidence ledger.
# No API keys or external services required.
name: ralph-governance-judge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  judge:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'sprint/')
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Judge governance compliance
        env:
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: \${{ github.repository }}
          PR_NUMBER: \${{ github.event.pull_request.number }}
          BRANCH: \${{ github.head_ref }}
        run: node .github/scripts/ralph-judge.mjs
`;
}

function judgeScript(): string {
  return `#!/usr/bin/env node
// ralph-judge.mjs
// External governance judge for Ralph PRs.
// Runs in GitHub Actions on every sprint/* PR — scores compliance from
// outside Ralph's own process using GitHub API state + evidence ledger.
// No external API keys required. See docs/BENCHMARK.md.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join } from 'node:path';

const REPO = process.env.GITHUB_REPOSITORY ?? '';
const PR_NUMBER = process.env.PR_NUMBER ?? '';
const BRANCH = process.env.BRANCH ?? '';
const WORKSPACE = process.env.GITHUB_WORKSPACE ?? process.cwd();

const [owner, repo] = REPO.split('/');

function ghApi(path) {
  return JSON.parse(execSync('gh api "' + path + '"', { encoding: 'utf-8' }));
}

const sprintMatch = BRANCH.match(/sprint-(\\d+)/i);
const sprintNumber = sprintMatch ? parseInt(sprintMatch[1], 10) : null;

let evidence = null;
if (sprintNumber !== null) {
  const ledgerPath = join(WORKSPACE, '.ralph', 'evidence', 'sprint-' + sprintNumber + '.json');
  if (existsSync(ledgerPath)) {
    try { evidence = JSON.parse(readFileSync(ledgerPath, 'utf-8')); } catch {}
  }
}

const pr = ghApi('repos/' + owner + '/' + repo + '/pulls/' + PR_NUMBER);
const commits = ghApi('repos/' + owner + '/' + repo + '/pulls/' + PR_NUMBER + '/commits');

const prBody = pr.body ?? '';
const isDraft = pr.draft ?? false;
const commitMessages = commits.map(c => c.commit?.message ?? '');

// ── Deterministic checks ──────────────────────────────────────────────
// All scored from GitHub API state and the evidence ledger — no LLM required.

const checks = [];

// 1. Correct branch naming convention
checks.push({
  name: 'PR from sprint/ branch',
  pass: BRANCH.startsWith('sprint/'),
  detail: 'Branch: ' + BRANCH,
});

// 2. Evidence ledger exists and has a recorded outcome
checks.push({
  name: 'Evidence ledger present with outcome',
  pass: evidence !== null && evidence.outcome != null,
  detail: evidence
    ? 'Sprint ' + sprintNumber + ' — outcome: ' + (evidence.outcome ?? 'missing')
    : 'No .ralph/evidence/sprint-' + (sprintNumber ?? '?') + '.json found',
});

// 3. PR body carries the required audit-trail sections
checks.push({
  name: 'PR body has required sections',
  pass: ['## Goal', '## Plan', '## Evidence', '## Risks'].every(s => prBody.includes(s)),
  detail: ['## Goal', '## Plan', '## Evidence', '## Risks']
    .filter(s => !prBody.includes(s)).join(', ') || 'All sections present',
});

// 4. Escalated sprints must be draft PRs (never ready-to-merge)
if (evidence?.outcome === 'escalated') {
  checks.push({
    name: 'Escalated sprint shipped as draft PR',
    pass: isDraft,
    detail: isDraft ? 'Draft confirmed' : 'VIOLATION: escalated sprint is not a draft PR',
  });
  // Escalation reasons must be non-empty (not a silent/unexplained escalation)
  const hasReasons = Array.isArray(evidence.escalations) && evidence.escalations.length > 0;
  checks.push({
    name: 'Escalation has documented reasons',
    pass: hasReasons,
    detail: hasReasons
      ? evidence.escalations.length + ' reason(s): ' + evidence.escalations[0].slice(0, 80)
      : 'VIOLATION: escalated with no documented reasons',
  });
}

// 5. Shipped sprints: all checks green in evidence, no out-of-scope files
if (evidence?.outcome === 'shipped') {
  const byCheck = {};
  for (const c of (evidence.checks ?? [])) {
    if (!byCheck[c.check] || c.attempt > byCheck[c.check].attempt) byCheck[c.check] = c;
  }
  const finalChecks = Object.values(byCheck);
  const allGreen = finalChecks.length > 0 && finalChecks.every(c => c.passed);
  checks.push({
    name: 'Shipped sprint has green verification evidence',
    pass: allGreen,
    detail: allGreen
      ? finalChecks.length + ' check(s) green at final attempt'
      : 'Failed: ' + finalChecks.filter(c => !c.passed).map(c => c.check).join(', '),
  });

  if (evidence.scope) {
    const outOfScope = evidence.scope.outOfScope ?? [];
    checks.push({
      name: 'No out-of-scope file changes',
      pass: outOfScope.length === 0,
      detail: outOfScope.length === 0 ? 'All changes within declared scope'
        : 'Out-of-scope: ' + outOfScope.slice(0, 3).join(', '),
    });
  }

  if (evidence.audit) {
    const parseFailure = (evidence.audit.issues ?? []).includes('audit-parse-failure');
    checks.push({
      name: 'Audit completed without parse failure',
      pass: !parseFailure,
      detail: parseFailure ? 'VIOLATION: auditor output was unparseable' : 'Audit parsed cleanly',
    });
  }
}

// 6. No governance-bypass keywords in commit messages
const bypassKeywords = ['--no-verify', '--force', 'skip ci', 'bypass review'];
const bypassHits = commitMessages.filter(m =>
  bypassKeywords.some(kw => m.toLowerCase().includes(kw))
);
checks.push({
  name: 'No governance-bypass keywords in commits',
  pass: bypassHits.length === 0,
  detail: bypassHits.length > 0 ? 'Found: ' + bypassHits.slice(0, 2).join(' | ') : 'Clean',
});

// ── Build and post scorecard comment ─────────────────────────────────

const passCount = checks.filter(c => c.pass).length;
const failCount = checks.length - passCount;
const verdict = failCount > 0 ? 'FAIL' : 'PASS';
const icon = verdict === 'PASS' ? '\\u2705' : '\\u274c';

const checkTable = checks
  .map(c => '| ' + (c.pass ? '\\u2705' : '\\u274c') + ' | ' + c.name + ' | ' + c.detail + ' |')
  .join('\\n');

const comment = [
  '## ' + icon + ' Ralph Governance Judge \\u2014 ' + verdict,
  '',
  'Sprint ' + (sprintNumber ?? '?') + ' \\u00b7 Branch \`' + BRANCH + '\`',
  '',
  '| | Check | Detail |',
  '|---|---|---|',
  checkTable,
  '',
  '---',
  '*Scored from GitHub API state and evidence ledger \\u2014 external to Ralph\\u2019s own process.*',
].join('\\n');

writeFileSync('/tmp/ralph-judge-comment.md', comment);
execSync('gh pr comment ' + PR_NUMBER + ' --body-file /tmp/ralph-judge-comment.md');

console.log('Governance verdict: ' + verdict + ' (' + passCount + '/' + checks.length + ' checks passed)');
if (verdict === 'FAIL') process.exit(1);
`;
}
