import type { ProjectContext } from "../context/types.js";
import { commitAll, push, createPR } from "../util/git.js";
import { log } from "../util/logger.js";

export function ship(
  ctx: ProjectContext,
  branchName: string,
  specName: string,
  parentBranch?: string,
): string {
  log("Committing and creating PR...");

  const commitMessage = `feat(${specName}): ${specName.replace(/-/g, " ")}`;
  commitAll(ctx.root, commitMessage);

  try {
    push(ctx.root, branchName);
  } catch {
    log(`  Push failed — code is committed locally on ${branchName}`);
  }

  const prTitle = `feat: ${specName.replace(/-/g, " ").replace(/^sprint \d+ /, "")}`;
  const chainNote = parentBranch && parentBranch !== ctx.git.baseBranch
    ? `\n\n**Chains from:** \`${parentBranch}\``
    : "";
  const prBody = `## Sprint: ${specName}\n\nAutonomously generated by Ralph.${chainNote}\n\nReview carefully before merging.`;

  try {
    return createPR(ctx.root, prTitle, prBody, ctx.git.baseBranch);
  } catch (err) {
    log(`  PR creation failed (non-GitHub remote?): ${err instanceof Error ? err.message : String(err)}`);
    log(`  Code is committed and pushed to ${branchName} — create a PR manually.`);
    return "";
  }
}
