import type { ProjectContext } from "../context/types.js";
import type { SprintOutcome } from "../types.js";
import { commitAll, push, createPR } from "../util/git.js";
import { log } from "../util/logger.js";

export interface ShipOptions {
  parentBranch?: string;
  /** Final sprint outcome — "blocked" commits locally and skips the PR */
  outcome?: SprintOutcome;
  /** Rendered audit-trail markdown (Goal / Plan / Evidence / Outcome) */
  evidenceMarkdown?: string;
}

export function ship(
  ctx: ProjectContext,
  branchName: string,
  specName: string,
  opts: ShipOptions = {},
): string {
  const outcome = opts.outcome || "shipped";
  const draft = outcome === "escalated";

  log("Committing changes...");
  const commitMessage = `feat(${specName}): ${specName.replace(/-/g, " ")}`;
  commitAll(ctx.root, commitMessage);

  if (outcome === "blocked") {
    log(`  Outcome: BLOCKED — work is committed locally on ${branchName}, no PR raised.`);
    log("  Review the failure report in .ralph/evidence/ and re-run after fixing, or change onVerifyFailure in .ralph.yaml.");
    return "";
  }

  try {
    push(ctx.root, branchName);
  } catch {
    log(`  Push failed — code is committed locally on ${branchName}`);
  }

  const prTitle = `feat: ${specName.replace(/-/g, " ").replace(/^sprint \d+ /, "")}`;
  const chainNote = opts.parentBranch && opts.parentBranch !== ctx.git.baseBranch
    ? `\n\n**Chains from:** \`${opts.parentBranch}\``
    : "";
  const prBody =
    (opts.evidenceMarkdown || `## Sprint: ${specName}\n\nAutonomously generated by Ralph.`) +
    chainNote +
    "\n\n---\nAutonomously generated by Ralph. Review carefully before merging.";

  try {
    return createPR(
      ctx.root,
      prTitle,
      prBody,
      ctx.git.baseBranch,
      ctx.git.provider,
      ctx.git.giteaApiUrl,
      ctx.git.giteaRepo,
      draft,
    );
  } catch (err) {
    log(`  PR creation failed: ${err instanceof Error ? err.message : String(err)}`);
    log(`  Code is committed and pushed to ${branchName} — create a PR manually.`);
    return "";
  }
}
