import { join, relative } from "node:path";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

export interface RalphConfig {
  spec?: string;
  baseBranch?: string;
}

const CONFIG_FILE = ".ralph.yaml";

export function loadConfig(root: string): RalphConfig | null {
  const configPath = join(root, CONFIG_FILE);
  if (!existsSync(configPath)) return null;
  const content = readFileSync(configPath, "utf-8");
  const config: RalphConfig = {};

  const specMatch = content.match(/^spec:\s*(.+)$/m);
  if (specMatch) config.spec = specMatch[1].trim();

  const branchMatch = content.match(/^baseBranch:\s*(.+)$/m);
  if (branchMatch) config.baseBranch = branchMatch[1].trim();

  return config;
}

export function saveConfig(root: string, config: RalphConfig): void {
  // Merge with existing config
  const existing = loadConfig(root) || {};
  const merged = { ...existing, ...config };

  const lines: string[] = [
    "# Ralph configuration (generated by ralph init, editable)",
  ];
  if (merged.spec) lines.push(`spec: ${merged.spec}`);
  if (merged.baseBranch) lines.push(`baseBranch: ${merged.baseBranch}`);
  writeFileSync(join(root, CONFIG_FILE), lines.join("\n") + "\n");
}
