import { join } from "node:path";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import type { AutonomyMode, VerifyFailurePolicy } from "./types.js";

export interface RalphConfig {
  spec?: string;
  baseBranch?: string;
  onVerifyFailure?: VerifyFailurePolicy;
  autonomy?: AutonomyMode;
}

const CONFIG_FILE = ".ralph.yaml";

const VERIFY_FAILURE_POLICIES: VerifyFailurePolicy[] = [
  "draft-pr",
  "block",
  "ship",
];

export function loadConfig(root: string): RalphConfig | null {
  const configPath = join(root, CONFIG_FILE);
  if (!existsSync(configPath)) return null;
  const content = readFileSync(configPath, "utf-8");
  const config: RalphConfig = {};

  const specMatch = content.match(/^spec:\s*(.+)$/m);
  if (specMatch) config.spec = specMatch[1].trim();

  const branchMatch = content.match(/^baseBranch:\s*(.+)$/m);
  if (branchMatch) config.baseBranch = branchMatch[1].trim();

  const verifyMatch = content.match(/^onVerifyFailure:\s*(.+)$/m);
  if (verifyMatch) {
    const value = verifyMatch[1].trim() as VerifyFailurePolicy;
    if (VERIFY_FAILURE_POLICIES.includes(value)) {
      config.onVerifyFailure = value;
    }
  }

  const autonomyMatch = content.match(/^autonomy:\s*(.+)$/m);
  if (autonomyMatch) {
    const value = autonomyMatch[1].trim() as AutonomyMode;
    if (value === "auto" || value === "plan-first") {
      config.autonomy = value;
    }
  }

  return config;
}

export function saveConfig(root: string, config: RalphConfig): void {
  // Merge with existing config
  const existing = loadConfig(root) || {};
  const merged = { ...existing, ...config };

  const lines: string[] = [
    "# Ralph configuration (generated by ralph init, editable)",
  ];
  if (merged.spec) lines.push(`spec: ${merged.spec}`);
  if (merged.baseBranch) lines.push(`baseBranch: ${merged.baseBranch}`);
  if (merged.onVerifyFailure)
    lines.push(`onVerifyFailure: ${merged.onVerifyFailure}`);
  if (merged.autonomy) lines.push(`autonomy: ${merged.autonomy}`);
  writeFileSync(join(root, CONFIG_FILE), lines.join("\n") + "\n");
}
